name: Tests

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GO
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - run: go version

      - name: Test
        run: go test ./configs